import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { schemaDescriptions } from "../src/schema/descriptions.js";

/** Relevant shape of Drizzle's committed migration journal. */
type DrizzleJournal = {
  /** Ordered migration entries. */
  entries: {
    /** Zero-based migration sequence number. */
    idx: number;
    /** Migration identifier used by Drizzle. */
    tag: string;
  }[];
};

/** Relevant shape of a committed Drizzle schema snapshot. */
type DrizzleSnapshot = {
  /** Snapshot tables keyed by their internal identifiers. */
  tables: Record<string, DrizzleTable>;
};

/** Table metadata recorded in a Drizzle snapshot. */
type DrizzleTable = {
  /** Columns keyed by their internal identifiers. */
  columns: Record<string, DrizzleColumn>;
  /** Foreign-key constraints keyed by their internal identifiers. */
  foreignKeys?: Record<string, DrizzleForeignKey>;
  /** Indexes keyed by their internal identifiers. */
  indexes?: Record<string, DrizzleIndex>;
  /** PostgreSQL table name. */
  name: string;
  /** Unique constraints keyed by their internal identifiers. */
  uniqueConstraints?: Record<
    string,
    {
      /** PostgreSQL column names covered by the constraint. */
      columns: string[];
      /** PostgreSQL constraint name. */
      name: string;
    }
  >;
};

/** Column metadata recorded in a Drizzle snapshot. */
type DrizzleColumn = {
  /** Default recorded in the snapshot, when present. */
  default?: string;
  /** PostgreSQL column name. */
  name: string;
  /** Whether the column rejects null values. */
  notNull: boolean;
  /** Whether the column belongs to the primary key. */
  primaryKey: boolean;
  /** Serialized PostgreSQL data type. */
  type: string;
};

/** Foreign-key metadata recorded in a Drizzle snapshot. */
type DrizzleForeignKey = {
  /** Source column names in constraint order. */
  columnsFrom: string[];
  /** Target column names in constraint order. */
  columnsTo: string[];
  /** PostgreSQL constraint name. */
  name: string;
  /** Referential action for deleted target rows. */
  onDelete?: string;
  /** Referential action for updated target rows. */
  onUpdate?: string;
  /** Referenced PostgreSQL table name. */
  tableTo: string;
};

/** Index metadata recorded in a Drizzle snapshot. */
type DrizzleIndex = {
  /** Indexed columns or expressions in index order. */
  columns: {
    /** Serialized column name or SQL expression. */
    expression: string;
    /** Whether the value is an SQL expression rather than a column name. */
    isExpression: boolean;
  }[];
  /** Whether the index enforces uniqueness. */
  isUnique: boolean;
  /** PostgreSQL index access method. */
  method: string;
  /** PostgreSQL index name. */
  name: string;
};

/** Generated documentation for one database table. */
type TableDoc = {
  /** Markdown output filename. */
  fileName: string;
  /** Complete generated Markdown document. */
  markdown: string;
  /** PostgreSQL table name. */
  tableName: string;
};

/** Warning prepended to every generated schema document. */
const generatedHeader =
  "<!-- Generated by `pnpm --filter @package/database db:generate:docs`. Do not edit by hand. -->";
/** Absolute directory containing this generator. */
const scriptDir = dirname(fileURLToPath(import.meta.url));
/** Absolute database package root. */
const databaseRoot = resolve(scriptDir, "..");
/** Absolute monorepo root. */
const repoRoot = resolve(databaseRoot, "../..");
/** Absolute directory containing committed Drizzle metadata. */
const drizzleMetaDir = join(databaseRoot, "drizzle", "meta");
/** Absolute directory for generated schema documentation. */
const outputDir = join(repoRoot, "docs", "database-schema");

/**
 * Regenerates Markdown documentation from the latest Drizzle snapshot.
 *
 * @rejects When migration metadata cannot be read or documentation cannot be written.
 */
async function main() {
  const snapshot = await readLatestSnapshot();
  const tableDocs = createTableDocs(snapshot);

  await cleanGeneratedMarkdown();
  await writeFile(
    join(outputDir, "index.md"),
    createIndexDoc(tableDocs),
    "utf8",
  );

  for (const tableDoc of tableDocs) {
    await writeFile(
      join(outputDir, tableDoc.fileName),
      tableDoc.markdown,
      "utf8",
    );
  }
}

/**
 * Reads the snapshot referenced by the latest migration journal entry.
 *
 * @returns The latest committed Drizzle schema snapshot.
 * @rejects When migration metadata cannot be read or parsed, or the journal is empty.
 */
async function readLatestSnapshot(): Promise<DrizzleSnapshot> {
  const journal = JSON.parse(
    await readFile(join(drizzleMetaDir, "_journal.json"), "utf8"),
  ) as DrizzleJournal;
  const latestEntry = journal.entries.at(-1);

  if (!latestEntry) {
    throw new Error("Drizzle journal does not contain any entries.");
  }

  const snapshotPath = join(
    drizzleMetaDir,
    `${String(latestEntry.idx).padStart(4, "0")}_snapshot.json`,
  );

  return JSON.parse(await readFile(snapshotPath, "utf8")) as DrizzleSnapshot;
}

/**
 * Removes existing generated Markdown files from the output directory.
 *
 * @rejects When the output directory cannot be created, read, or cleaned.
 */
async function cleanGeneratedMarkdown() {
  await mkdir(outputDir, { recursive: true });
  const entries = await readdir(outputDir, { withFileTypes: true });

  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map((entry) => unlink(join(outputDir, entry.name))),
  );
}

/**
 * Builds alphabetically ordered table documents from a Drizzle snapshot.
 *
 * @param snapshot - Snapshot containing the committed database tables.
 * @returns Generated documents ordered by table name.
 */
function createTableDocs(snapshot: DrizzleSnapshot): TableDoc[] {
  return Object.values(snapshot.tables)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((table) => ({
      fileName: `${slugifyTableName(table.name)}.md`,
      markdown: createTableDoc(table),
      tableName: table.name,
    }));
}

/**
 * Converts a PostgreSQL table name to its documentation filename stem.
 *
 * @param tableName - Underscore-delimited PostgreSQL table name.
 * @returns The hyphen-delimited filename stem.
 */
function slugifyTableName(tableName: string): string {
  return tableName.replaceAll("_", "-");
}

/**
 * Creates the schema documentation index.
 *
 * @param tableDocs - Generated table documents in display order.
 * @returns Markdown linking to every generated table document.
 */
function createIndexDoc(tableDocs: TableDoc[]): string {
  const tableRows = tableDocs
    .map((tableDoc) => `- [\`${tableDoc.tableName}\`](./${tableDoc.fileName})`)
    .join("\n");

  return `${generatedHeader}

# Database Schema

Generated schema documentation for committed Drizzle tables.

${tableRows}
`;
}

/**
 * Creates schema documentation for one table.
 *
 * @param table - Drizzle metadata for the table.
 * @returns The complete table Markdown document.
 */
function createTableDoc(table: DrizzleTable): string {
  const description = schemaDescriptions[table.name]?.description;
  const columnRows = Object.values(table.columns)
    .map((column) => createColumnRow(table, column))
    .join("\n");
  const indexRows = Object.values(table.indexes ?? {})
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(
      (index) =>
        `| \`${escapeMarkdown(index.name)}\` | ${index.isUnique ? "yes" : "no"} | \`${escapeMarkdown(index.method)}\` | ${index.columns.map(formatIndexColumn).join(", ")} |`,
    )
    .join("\n");

  return `${generatedHeader}

# ${table.name}

${description ?? "No table description has been added yet."}

## Columns

| Column | Type | Required | Key | Default | Relation | Description | Example |
| --- | --- | --- | --- | --- | --- | --- | --- |
${columnRows}
${indexRows ? `\n## Indexes\n\n| Name | Unique | Method | Columns |\n| --- | --- | --- | --- |\n${indexRows}\n` : ""}`;
}

/**
 * Creates a Markdown row describing one table column.
 *
 * @param table - Table that owns the column.
 * @param column - Column metadata to render.
 * @returns A pipe-delimited Markdown table row.
 */
function createColumnRow(table: DrizzleTable, column: DrizzleColumn): string {
  const columnDescription =
    schemaDescriptions[table.name]?.columns?.[column.name];

  return [
    `\`${escapeMarkdown(column.name)}\``,
    `\`${escapeMarkdown(column.type)}\``,
    column.notNull ? "yes" : "no",
    formatColumnKey(table, column),
    column.default ? `\`${escapeMarkdown(column.default)}\`` : "",
    formatColumnRelation(table, column.name),
    columnDescription?.description ?? "",
    formatExample(columnDescription?.example),
  ]
    .map((value) => escapeTableCell(value))
    .join(" | ")
    .replace(/^/, "| ")
    .replace(/$/, " |");
}

/**
 * Summarizes the key roles held by a column.
 *
 * @param table - Table that owns the column.
 * @param column - Column to inspect.
 * @returns Comma-delimited primary, unique, and foreign-key labels.
 */
function formatColumnKey(table: DrizzleTable, column: DrizzleColumn): string {
  const keys = [];

  if (column.primaryKey) {
    keys.push("PK");
  }

  if (
    Object.values(table.uniqueConstraints ?? {}).some(
      (constraint) =>
        constraint.columns.length === 1 &&
        constraint.columns.includes(column.name),
    ) ||
    Object.values(table.indexes ?? {}).some(
      (index) =>
        index.isUnique &&
        index.columns.length === 1 &&
        index.columns.some(
          (indexColumn) =>
            !indexColumn.isExpression && indexColumn.expression === column.name,
        ),
    )
  ) {
    keys.push("unique");
  }

  if (
    Object.values(table.foreignKeys ?? {}).some((foreignKey) =>
      foreignKey.columnsFrom.includes(column.name),
    )
  ) {
    keys.push("FK");
  }

  return keys.join(", ");
}

/**
 * Formats foreign-key targets and non-default referential actions.
 *
 * @param table - Table that owns the source column.
 * @param columnName - Source column name.
 * @returns Comma-delimited Markdown relation descriptions.
 */
function formatColumnRelation(table: DrizzleTable, columnName: string): string {
  const relations = Object.values(table.foreignKeys ?? {})
    .filter((foreignKey) => foreignKey.columnsFrom.includes(columnName))
    .map((foreignKey) => {
      const columnIndex = foreignKey.columnsFrom.indexOf(columnName);
      const targetColumn = foreignKey.columnsTo[columnIndex];
      const actions = [
        foreignKey.onDelete && foreignKey.onDelete !== "no action"
          ? `on delete ${foreignKey.onDelete}`
          : undefined,
        foreignKey.onUpdate && foreignKey.onUpdate !== "no action"
          ? `on update ${foreignKey.onUpdate}`
          : undefined,
      ].filter(Boolean);

      return `\`${foreignKey.tableTo}.${targetColumn}\`${actions.length > 0 ? ` (${actions.join(", ")})` : ""}`;
    });

  return relations.join(", ");
}

/**
 * Formats one indexed column or expression as inline code.
 *
 * @param column - Indexed value metadata.
 * @returns Escaped Markdown inline code.
 */
function formatIndexColumn(column: DrizzleIndex["columns"][number]): string {
  return `\`${escapeMarkdown(column.expression)}\``;
}

/**
 * Formats a schema example as inline code.
 *
 * @param example - Example value from the schema description registry.
 * @returns Escaped inline code, or an empty string when absent.
 */
function formatExample(example: unknown): string {
  if (example === undefined) {
    return "";
  }

  if (typeof example === "string") {
    return `\`${escapeMarkdown(example)}\``;
  }

  return `\`${escapeMarkdown(JSON.stringify(example))}\``;
}

/**
 * Escapes content for use inside a Markdown table cell.
 *
 * @param value - Unescaped cell content.
 * @returns Cell content with pipes and line breaks escaped.
 */
function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

/**
 * Converts a value to Markdown text and escapes table separators.
 *
 * @param value - Value to render.
 * @returns String value with pipe characters escaped.
 */
function escapeMarkdown(value: unknown): string {
  return String(value).replaceAll("|", "\\|");
}

await main();
