import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { schemaDescriptions } from "../src/schema/descriptions.js";

type DrizzleJournal = {
  entries: {
    idx: number;
    tag: string;
  }[];
};

type DrizzleSnapshot = {
  tables: Record<string, DrizzleTable>;
};

type DrizzleTable = {
  columns: Record<string, DrizzleColumn>;
  foreignKeys?: Record<string, DrizzleForeignKey>;
  indexes?: Record<string, DrizzleIndex>;
  name: string;
  uniqueConstraints?: Record<
    string,
    {
      columns: string[];
      name: string;
    }
  >;
};

type DrizzleColumn = {
  default?: string;
  name: string;
  notNull: boolean;
  primaryKey: boolean;
  type: string;
};

type DrizzleForeignKey = {
  columnsFrom: string[];
  columnsTo: string[];
  name: string;
  onDelete?: string;
  onUpdate?: string;
  tableTo: string;
};

type DrizzleIndex = {
  columns: {
    expression: string;
    isExpression: boolean;
  }[];
  isUnique: boolean;
  method: string;
  name: string;
};

type TableDoc = {
  fileName: string;
  markdown: string;
  tableName: string;
};

const generatedHeader =
  "<!-- Generated by `pnpm --filter @package/database db:generate:docs`. Do not edit by hand. -->";
const scriptDir = dirname(fileURLToPath(import.meta.url));
const databaseRoot = resolve(scriptDir, "..");
const repoRoot = resolve(databaseRoot, "../..");
const drizzleMetaDir = join(databaseRoot, "drizzle", "meta");
const outputDir = join(repoRoot, "docs", "database-schema");

async function main() {
  const snapshot = await readLatestSnapshot();
  const tableDocs = createTableDocs(snapshot);

  await cleanGeneratedMarkdown();
  await writeFile(
    join(outputDir, "index.md"),
    createIndexDoc(tableDocs),
    "utf8",
  );

  for (const tableDoc of tableDocs) {
    await writeFile(
      join(outputDir, tableDoc.fileName),
      tableDoc.markdown,
      "utf8",
    );
  }
}

async function readLatestSnapshot(): Promise<DrizzleSnapshot> {
  const journal = JSON.parse(
    await readFile(join(drizzleMetaDir, "_journal.json"), "utf8"),
  ) as DrizzleJournal;
  const latestEntry = journal.entries.at(-1);

  if (!latestEntry) {
    throw new Error("Drizzle journal does not contain any entries.");
  }

  const snapshotPath = join(
    drizzleMetaDir,
    `${String(latestEntry.idx).padStart(4, "0")}_snapshot.json`,
  );

  return JSON.parse(await readFile(snapshotPath, "utf8")) as DrizzleSnapshot;
}

async function cleanGeneratedMarkdown() {
  await mkdir(outputDir, { recursive: true });
  const entries = await readdir(outputDir, { withFileTypes: true });

  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map((entry) => unlink(join(outputDir, entry.name))),
  );
}

function createTableDocs(snapshot: DrizzleSnapshot): TableDoc[] {
  return Object.values(snapshot.tables)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((table) => ({
      fileName: `${slugifyTableName(table.name)}.md`,
      markdown: createTableDoc(table),
      tableName: table.name,
    }));
}

function slugifyTableName(tableName: string): string {
  return tableName.replaceAll("_", "-");
}

function createIndexDoc(tableDocs: TableDoc[]): string {
  const tableRows = tableDocs
    .map((tableDoc) => `- [\`${tableDoc.tableName}\`](./${tableDoc.fileName})`)
    .join("\n");

  return `${generatedHeader}

# Database Schema

Generated schema documentation for committed Drizzle tables.

${tableRows}
`;
}

function createTableDoc(table: DrizzleTable): string {
  const description = schemaDescriptions[table.name]?.description;
  const columnRows = Object.values(table.columns)
    .map((column) => createColumnRow(table, column))
    .join("\n");
  const indexRows = Object.values(table.indexes ?? {})
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(
      (index) =>
        `| \`${escapeMarkdown(index.name)}\` | ${index.isUnique ? "yes" : "no"} | \`${escapeMarkdown(index.method)}\` | ${index.columns.map(formatIndexColumn).join(", ")} |`,
    )
    .join("\n");

  return `${generatedHeader}

# ${table.name}

${description ?? "No table description has been added yet."}

## Columns

| Column | Type | Required | Key | Default | Relation | Description | Example |
| --- | --- | --- | --- | --- | --- | --- | --- |
${columnRows}
${indexRows ? `\n## Indexes\n\n| Name | Unique | Method | Columns |\n| --- | --- | --- | --- |\n${indexRows}\n` : ""}`;
}

function createColumnRow(table: DrizzleTable, column: DrizzleColumn): string {
  const columnDescription =
    schemaDescriptions[table.name]?.columns?.[column.name];

  return [
    `\`${escapeMarkdown(column.name)}\``,
    `\`${escapeMarkdown(column.type)}\``,
    column.notNull ? "yes" : "no",
    formatColumnKey(table, column),
    column.default ? `\`${escapeMarkdown(column.default)}\`` : "",
    formatColumnRelation(table, column.name),
    columnDescription?.description ?? "",
    formatExample(columnDescription?.example),
  ]
    .map((value) => escapeTableCell(value))
    .join(" | ")
    .replace(/^/, "| ")
    .replace(/$/, " |");
}

function formatColumnKey(table: DrizzleTable, column: DrizzleColumn): string {
  const keys = [];

  if (column.primaryKey) {
    keys.push("PK");
  }

  if (
    Object.values(table.uniqueConstraints ?? {}).some(
      (constraint) =>
        constraint.columns.length === 1 &&
        constraint.columns.includes(column.name),
    ) ||
    Object.values(table.indexes ?? {}).some(
      (index) =>
        index.isUnique &&
        index.columns.length === 1 &&
        index.columns.some(
          (indexColumn) =>
            !indexColumn.isExpression && indexColumn.expression === column.name,
        ),
    )
  ) {
    keys.push("unique");
  }

  if (
    Object.values(table.foreignKeys ?? {}).some((foreignKey) =>
      foreignKey.columnsFrom.includes(column.name),
    )
  ) {
    keys.push("FK");
  }

  return keys.join(", ");
}

function formatColumnRelation(table: DrizzleTable, columnName: string): string {
  const relations = Object.values(table.foreignKeys ?? {})
    .filter((foreignKey) => foreignKey.columnsFrom.includes(columnName))
    .map((foreignKey) => {
      const columnIndex = foreignKey.columnsFrom.indexOf(columnName);
      const targetColumn = foreignKey.columnsTo[columnIndex];
      const actions = [
        foreignKey.onDelete && foreignKey.onDelete !== "no action"
          ? `on delete ${foreignKey.onDelete}`
          : undefined,
        foreignKey.onUpdate && foreignKey.onUpdate !== "no action"
          ? `on update ${foreignKey.onUpdate}`
          : undefined,
      ].filter(Boolean);

      return `\`${foreignKey.tableTo}.${targetColumn}\`${actions.length > 0 ? ` (${actions.join(", ")})` : ""}`;
    });

  return relations.join(", ");
}

function formatIndexColumn(column: DrizzleIndex["columns"][number]): string {
  return `\`${escapeMarkdown(column.expression)}\``;
}

function formatExample(example: unknown): string {
  if (example === undefined) {
    return "";
  }

  if (typeof example === "string") {
    return `\`${escapeMarkdown(example)}\``;
  }

  return `\`${escapeMarkdown(JSON.stringify(example))}\``;
}

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

function escapeMarkdown(value: unknown): string {
  return String(value).replaceAll("|", "\\|");
}

await main();
