import { writeFile } from "node:fs/promises";
import { createThemeCss } from "@tanstack/highlight/theme";
import { githubDarkTheme } from "@tanstack/highlight/themes/github-dark";
import { githubLightTheme } from "@tanstack/highlight/themes/github-light";

await writeFile(
  new URL("../theme.css", import.meta.url),
  `/* Generated by pnpm --filter @package/markdown generate:theme. */\n${createThemeCss(
    {
      codeBlockSelector: ".markdown-content pre.th-code",
      dark: githubDarkTheme,
      darkSelector: ".dark .markdown-content",
      light: githubLightTheme,
      lightSelector: ":root .markdown-content",
    },
  )}\n`,
);
