ALTER TABLE "collection_item" DROP CONSTRAINT "collection_item_private_metadata_consistent";--> statement-breakpoint
ALTER TABLE "collection_item_image" DROP CONSTRAINT "collection_item_image_deletion_metadata_consistent";--> statement-breakpoint
ALTER TABLE "product" DROP CONSTRAINT "product_private_metadata_consistent";--> statement-breakpoint
ALTER TABLE "product_image" DROP CONSTRAINT "product_image_deletion_metadata_consistent";--> statement-breakpoint
ALTER TABLE "user_collection" DROP CONSTRAINT "user_collection_private_metadata_consistent";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resources_private_metadata_consistent";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resources_deletion_metadata_consistent";--> statement-breakpoint
ALTER TABLE "collection_image" ALTER COLUMN "uploaded_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "collection_item_image" ALTER COLUMN "uploaded_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "owner_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_image" ALTER COLUMN "uploaded_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "feature_flag_user_overrides" ALTER COLUMN "created_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "feature_flag_user_overrides" ALTER COLUMN "updated_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "feature_flags" ALTER COLUMN "created_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "feature_flags" ALTER COLUMN "updated_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "resource_categories" ALTER COLUMN "created_by_clerk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "collection_item" ADD CONSTRAINT "collection_item_private_metadata_consistent" CHECK ((not "collection_item"."is_private" and num_nonnulls("collection_item"."private_reason", "collection_item"."privated_at", "collection_item"."privated_by_clerk_id") = 0) or ("collection_item"."is_private" and (num_nonnulls("collection_item"."private_reason", "collection_item"."privated_at", "collection_item"."privated_by_clerk_id") = 0 or ("collection_item"."private_reason" is not null and "collection_item"."privated_at" is not null))));--> statement-breakpoint
ALTER TABLE "collection_item_image" ADD CONSTRAINT "collection_item_image_deletion_metadata_consistent" CHECK (("collection_item_image"."deleted_at" is null and "collection_item_image"."deleted_by_clerk_id" is null and "collection_item_image"."deleted_by_role" is null) or ("collection_item_image"."deleted_at" is not null and "collection_item_image"."deleted_by_role" is not null));--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "product_private_metadata_consistent" CHECK ((not "product"."is_private" and num_nonnulls("product"."private_reason", "product"."privated_at", "product"."privated_by_clerk_id") = 0) or ("product"."is_private" and (num_nonnulls("product"."private_reason", "product"."privated_at", "product"."privated_by_clerk_id") = 0 or ("product"."private_reason" is not null and "product"."privated_at" is not null))));--> statement-breakpoint
ALTER TABLE "product_image" ADD CONSTRAINT "product_image_deletion_metadata_consistent" CHECK (("product_image"."deleted_at" is null and "product_image"."deleted_by_clerk_id" is null and "product_image"."deleted_by_role" is null) or ("product_image"."deleted_at" is not null and "product_image"."deleted_by_role" is not null));--> statement-breakpoint
ALTER TABLE "user_collection" ADD CONSTRAINT "user_collection_private_metadata_consistent" CHECK ((not "user_collection"."is_private" and num_nonnulls("user_collection"."private_reason", "user_collection"."privated_at", "user_collection"."privated_by_clerk_id") = 0) or ("user_collection"."is_private" and (num_nonnulls("user_collection"."private_reason", "user_collection"."privated_at", "user_collection"."privated_by_clerk_id") = 0 or ("user_collection"."private_reason" is not null and "user_collection"."privated_at" is not null))));--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_private_metadata_consistent" CHECK ((not "resources"."is_private" and num_nonnulls("resources"."private_reason", "resources"."privated_at", "resources"."privated_by_clerk_id") = 0) or ("resources"."is_private" and (num_nonnulls("resources"."private_reason", "resources"."privated_at", "resources"."privated_by_clerk_id") = 0 or ("resources"."private_reason" is not null and "resources"."privated_at" is not null))));--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_deletion_metadata_consistent" CHECK (("resources"."deleted_at" is null and "resources"."deleted_by_clerk_id" is null and "resources"."deleted_by_role" is null) or ("resources"."deleted_at" is not null and "resources"."deleted_by_role" is not null));