/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: e3619343fcab01082ca7eb9c84a00cfd)
interface __BaseEnv_Env {
  CLERK_WEBHOOK_TARGETS?: KVNamespace;
  APP_ENV: "development" | "preview" | "production";
  BUNNY_IMAGE_FOLDER_PREFIX: "images/dev" | "images/preview" | "images";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface DevelopmentEnv {
    CLERK_WEBHOOK_TARGETS: KVNamespace;
    APP_ENV: "development";
    BUNNY_IMAGE_FOLDER_PREFIX: "images/dev";
  }
  interface PreviewEnv {
    APP_ENV: "preview";
    BUNNY_IMAGE_FOLDER_PREFIX: "images/preview";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "APP_ENV" | "BUNNY_IMAGE_FOLDER_PREFIX">
    > {}
}
