/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 184a6bbcaaecf3dc9e793dd74ddfc376)
interface __BaseEnv_Env {
  CLERK_WEBHOOK_TARGETS?: KVNamespace;
  APP_ENV: "development" | "preview" | "production";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface DevelopmentEnv {
    CLERK_WEBHOOK_TARGETS: KVNamespace;
    APP_ENV: "development";
  }
  interface PreviewEnv {
    APP_ENV: "preview";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
