import process from "node:process";
import { createWebServerEnv } from "./server.schema";

export const serverEnv = createWebServerEnv({
  ASSET_FOLDER_PREFIX: process.env.ASSET_FOLDER_PREFIX,
  AXIOM_DATASET: process.env.AXIOM_DATASET,
  AXIOM_EDGE_DOMAIN: process.env.AXIOM_EDGE_DOMAIN,
  AXIOM_TOKEN: process.env.AXIOM_TOKEN,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  BUNNY_IMAGE_FOLDER_PREFIX: process.env.BUNNY_IMAGE_FOLDER_PREFIX,
  LOGGER: process.env.LOGGER,
  LOG_DEPLOYMENT_ID: process.env.LOG_DEPLOYMENT_ID,
  LOG_DEPLOYMENT_TARGET: process.env.LOG_DEPLOYMENT_TARGET,
  LOG_LEVEL: process.env.LOG_LEVEL,
  LOG_PROXY_CLIENT_KEY: process.env.LOG_PROXY_CLIENT_KEY,
  BUNNY_CDN_BASE_URL: process.env.BUNNY_CDN_BASE_URL,
  BUNNY_CDN_TOKEN_KEY: process.env.BUNNY_CDN_TOKEN_KEY,
  BUNNY_RESOURCE_FOLDER_PREFIX: process.env.BUNNY_RESOURCE_FOLDER_PREFIX,
  BUNNY_STORAGE_ACCESS_KEY: process.env.BUNNY_STORAGE_ACCESS_KEY,
  BUNNY_STORAGE_ENDPOINT: process.env.BUNNY_STORAGE_ENDPOINT,
  BUNNY_STORAGE_ZONE_NAME: process.env.BUNNY_STORAGE_ZONE_NAME,
});
