import process from "node:process";
import { createWebServerEnv } from "./server.schema";

export const serverEnv = createWebServerEnv({
  AXIOM_DATASET: process.env.AXIOM_DATASET,
  AXIOM_EDGE_DOMAIN: process.env.AXIOM_EDGE_DOMAIN,
  AXIOM_TOKEN: process.env.AXIOM_TOKEN,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  IMAGE_FOLDER_PREFIX: process.env.IMAGE_FOLDER_PREFIX,
  LOGGER: process.env.LOGGER,
  LOG_DEPLOYMENT_ID: process.env.LOG_DEPLOYMENT_ID,
  LOG_DEPLOYMENT_TARGET: process.env.LOG_DEPLOYMENT_TARGET,
  LOG_LEVEL: process.env.LOG_LEVEL,
  LOG_PROXY_CLIENT_KEY: process.env.LOG_PROXY_CLIENT_KEY,
  RESOURCE_CDN_BASE_URL: process.env.RESOURCE_CDN_BASE_URL,
  RESOURCE_FOLDER_PREFIX: process.env.RESOURCE_FOLDER_PREFIX,
  RESOURCE_STORAGE_ACCESS_KEY: process.env.RESOURCE_STORAGE_ACCESS_KEY,
  RESOURCE_STORAGE_ENDPOINT: process.env.RESOURCE_STORAGE_ENDPOINT,
  RESOURCE_STORAGE_ZONE_NAME: process.env.RESOURCE_STORAGE_ZONE_NAME,
});
